### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by chlab** [aexmachina/jquery-qubit#5]
Hi Simon
I'm using jquery-qubit together with jquery-bonsai. First of all: thanks for the great plugin, it was exactly what I was looking for, no more, no less (although a few more callbacks would be nice :)).

I am using bonsai for a pretty big tree: 10-20 root lists with 5-30 sub lists each, which in turn each contain another 10-20 entries. At this size, qubit has some performance issues (lags when toggling checkboxes). I checked the script and one reason could be that you use `.parents()` a lot, which will search all the way up through the DOM. The main reason however is this code (in `setChecked`):

```
if( !event || !event.doneIds || event.doneIds.indexOf(checkbox.id) == -1 ) {
    event = event || {type: 'change'};
    event.doneIds = event.doneIds || [];
    event.doneIds.push(checkbox.id);
    $(checkbox).trigger(event);
}
```

This triggers change events on all child checkboxes, which in turn probably triggers chain events all the way up the tree again. What's this for and is this needed? I commented it out and everything still works fine (better actually, way faster).

Here are my performance optimizations if you're interested in merging them into your repo: [pull request](https://github.com/aexmachina/jquery-qubit/pull/4).

Cheers

**Comment by dchuquilla** [comment]
Hi all, thanks for a usefull plugin, it helps me a lot, i have a question, is there a call back that triggers after after all child items change?,  i am doing a process that works with all checked items,  but in Firefox it is going in asynchronously and my process is faster than child changes.

**Comment by aexmachina** [comment]
There's nothing asynchronous about event processing. I'd say that you're probably adding your event listener before bonsai, so you're getting the event before bonsai has done its thing. Feel free to open a new issue if this doesn't fix your problem.
